name: Deploy to VPS

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      
      - name: Install npm dependencies
        run: npm i

      - name: Run build task
        run: npm run build
        
      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SERVER_PRIVATE_KEY }}
            REMOTE_HOST: ${{ secrets.DEPLOY_SERVER_HOST }}
            REMOTE_USER: ${{ secrets.DEPLOY_SERVER_USER }}
            TARGET: /home/${{ secrets.DEPLOY_SERVER_USER }}/laura
            
      - name: Start
        run: npm run start
